import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ModeToggle } from "@/components/mode-toggle";
import { Suspense } from "react";
import Loading from "./loading";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="flex h-screen flex-col">
          <div className="relative z-20 flex flex-col  justify-between  gap-4 py-6 shadow">
            <div className="container flex justify-between">
              <div className="flex flex-col gap-2">
              <h1 className="text-lg font-semibold text-slate-700 dark:text-slate-400">
                <Link href="/">{process.env.ROADMAP}</Link>
              </h1>

              <div className="flex gap-2">
                <Button variant="secondary" size="sm" asChild>
                  <Link href="/">Status</Link>
                </Button>
                <Button variant="secondary" size="sm" asChild>
                  <Link href="/lead">Assigned</Link>
                </Button>
                <Button variant="secondary" size="sm" asChild>
                  <Link href="/list">List</Link>
                </Button>
              </div>
              </div>

              <ModeToggle/>
            </div>
          </div>

          <Suspense fallback={<Loading/>}>
            <ScrollArea>
              <div className="container mx-auto mt-8 flex flex-col gap-2 pb-4">
                {children}
              </div>
            </ScrollArea>
          </Suspense>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
